### ISSUE TITLE
Upgrade to v204 of Sift Science API

### ISSUE THREAD

**Issue by getplank** [otothea/yield-siftscience#2]
Upgrade to v204 of Sift Science API - support for individual abuse_types and granular support for synchronous scores and workflow status

Sift Science is deprecating formulas and actions. [https://siftscience.com/resources/tutorials/formulas](https://siftscience.com/resources/tutorials/formulas)

These are being replaced by 

- Specific abuse types. [https://siftscience.com/developers/docs/curl/decisions-api/decision-status](https://siftscience.com/developers/docs/curl/decisions-api/decision-status)
- Synchronous scores. [https://siftscience.com/developers/docs/curl/score-api/synchronous-scores]( https://siftscience.com/developers/docs/curl/score-api/synchronous-scores)
- Synchronous workflow status. [https://siftscience.com/developers/docs/curl/workflows-api/workflow-decisions](https://siftscience.com/developers/docs/curl/workflows-api/workflow-decisions)

**Comment by otothea** [comment]
Forgot to add issue number to commit message: 98dee02962b8f10c4c583c0b03e1c6dfa3d77507
