### ISSUE TITLE
Support applying decisions to users

### ISSUE THREAD

**Issue by officert** [otothea/yield-siftscience#5]
I'd like to be able to apply decisions to users:
https://siftscience.com/developers/docs/curl/decisions-api/apply-decisions
Right now it looks like your library only support getting decisions for users.

I'm happy to try and submit a pull-request.

**Comment by otothea** [comment]
Hey @officert. Thanks for letting me know about the new APIs. I added support to list and apply decisions on a new branch `feature/apply-decisions`. Everything appears to be working fine, can you please check it out and confirm? If it looks good I will merge it and update npm

**Comment by otothea** [comment]
Here is the pull request #6. You may notice I also added a lot of constants that I saw were missing as I was reading through the updated docs.

**Comment by otothea** [comment]
@officert bump ^
